CREATE TABLE IF NOT EXISTS EVENTS(
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    STATUS VARCHAR(64) NOT NULL DEFAULT 'scheduled',
    CREATED_AT TIMESTAMP DEFAULT NOW(),
    HAVE_NOTIFICATION BOOLEAN DEFAULT FALSE,
    EVENT_DATE TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS ARCHIVE(
    ID SERIAL PRIMARY KEY,
    EVENT_ID INT NOT NULL,
    ADDED_AT TIMESTAMP NOT NULL
);
